"""empty message

Revision ID: e1390d1ad0c2
Revises: a7643359d9e2
Create Date: 2025-10-19 22:49:36.005087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1390d1ad0c2'
down_revision = 'a7643359d9e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('VIDEO', 'PICTURE', name='typeenum'), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['Post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Media')
    # ### end Alembic commands ###
